name: Build macOS App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install pyinstaller pillow
      - run: pyinstaller --onefile --windowed set_image_dates.py --name "图片时间修正工具" --icon=icon.icns
      - uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/图片时间修正工具.app
