name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller pillow

      - name: Build macOS App
        run: |
          # 用英文名构建（防止路径编码问题）
          pyinstaller --onefile --windowed set_image_dates.py \
                      --name "ImageDateFixer" \
                      --icon=icon.icns || true

      - name: List dist files
        run: ls -R dist

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageDateFixer-macOS
          path: dist/*
