name: Build macOS App (Intel + ARM)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-mac:
    name: Build macOS Universal App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build macOS App (Universal Binary)
        run: |
          pyinstaller --onefile --windowed --name "图片时间修正工具" fix_image_time.py
          mkdir -p dist_universal
          cp -r dist/图片时间修正工具 dist_universal/
          cd dist_universal
          zip -r 图片时间修正工具-mac通用版.zip 图片时间修正工具

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 图片时间修正工具-mac通用版
          path: dist_universal/图片时间修正工具-mac通用版.zip
